-- Minimal AddressBook schema for testing
CREATE TABLE ZABCDRECORD (
    Z_PK INTEGER PRIMARY KEY,
    Z_ENT INTEGER,
    Z_OPT INTEGER,
    ZFIRSTNAME VARCHAR,
    ZLASTNAME VARCHAR,
    ZMIDDLENAME VARCHAR,
    ZNICKNAME VARCHAR,
    ZORGANIZATION VARCHAR,
    ZDEPARTMENT VARCHAR,
    ZJOBTITLE VARCHAR,
    ZUNIQUEID VARCHAR
);

CREATE TABLE ZABCDPHONENUMBER (
    Z_PK INTEGER PRIMARY KEY,
    Z_ENT INTEGER,
    Z_OPT INTEGER,
    ZOWNER INTEGER,
    ZFULLNUMBER VARCHAR,
    ZLABEL VARCHAR
);

CREATE TABLE ZABCDEMAILADDRESS (
    Z_PK INTEGER PRIMARY KEY,
    Z_ENT INTEGER,
    Z_OPT INTEGER,
    ZOWNER INTEGER,
    ZADDRESS VARCHAR,
    ZADDRESSNORMALIZED VARCHAR,
    ZLABEL VARCHAR
);

CREATE INDEX ZABCDPHONENUMBER_ZOWNER_INDEX ON ZABCDPHONENUMBER (ZOWNER);
CREATE INDEX ZABCDEMAILADDRESS_ZOWNER_INDEX ON ZABCDEMAILADDRESS (ZOWNER);
